services:
  - type: web
    name: career-guidance-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
